# The configuration of server.
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# The configuration of Spring.
spring:
  # The configuration of persistent database.
  datasource:
    url: jdbc:mysql://8.208.112.119:13078/estate_agency_system?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: BKbU8BQzQPhm0wetAI
    driver-class-name: com.mysql.cj.jdbc.Driver

  # The configuration of redis.
  redis:
    host: 8.208.112.119
    port: 19047
    password: B8vgLBK4Bg322xh2

# The configuration of MybatisPlus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: stacs.estate.cs5031p3code.model
