# The configuration of server.
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# The configuration of Spring.
spring:
  # The configuration of persistent database.
  datasource:
    url: jdbc:mysql://localhost:3306/estate_agency_system?characterEncoding=utf-8&serverTimezone=UTC
    #    url: jdbc:mariadb://hz65.host.cs.st-andrews.ac.uk:3306/hz65_estate_agency_system?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    #    username: hz65
    password: 123456
    #    password: 875J3kAG0w1.Pb
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.mariadb.jdbc.Driver
  # The configuration of redis.
  redis:
    host: 127.0.0.1
    port: 6379
    username: Henry

# The configuration of MybatisPlus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: stacs.estate.cs5031p3code.model
